(function(){'use strict';var P='nc-';var PROXY='/api/nutrition-proxy.php';var USDA_KEY='uDDftliebrLVUZlTmKeEspBlw77WphcTSFBjqTRC';var USDA_URL='https://api.nal.usda.gov/fdc/v1';var $=function(id){return document.getElementById(P+id);};var els={};var mealItems=[];var selectedFood=null;var dailyGoal=2000;var searchResults=[];function cacheDom(){els={themeBtn:$('theme-toggle'),searchInput:$('search-input'),searchBtn:$('search-btn'),loader:$('loader'),error:$('error'),resultsBox:$('results'),servingArea:$('serving-area'),qtyInput:$('qty'),servingSelect:$('serving-sel'),addBtn:$('add-btn'),totalCal:$('total-cal'),totalPro:$('total-pro'),totalCarb:$('total-carb'),totalFat:$('total-fat'),totalFiber:$('total-fiber'),totalSugar:$('total-sugar'),totalSodium:$('total-sodium'),totalSatFat:$('total-satfat'),totalCholesterol:$('total-chol'),totalPotassium:$('total-potassium'),proPct:$('pro-pct'),carbPct:$('carb-pct'),fatPct:$('fat-pct'),proSeg:$('pro-seg'),carbSeg:$('carb-seg'),fatSeg:$('fat-seg'),goalBar:$('goal-bar'),goalPct:$('goal-pct'),goalDisplay:$('goal-display'),goalInput:$('goal-input'),goalSetBtn:$('goal-set'),tableBody:$('table-body'),tableWrap:$('table-wrap'),emptyState:$('empty'),clearBtn:$('clear-btn'),sourceInfo:$('source-info'),selectedName:$('selected-name'),selectedInfo:$('selected-info'),detailPanel:$('detail-panel'),itemCount:$('item-count'),};}
function init(){cacheDom();loadState();initTheme();bindEvents();updateUI();}
function loadState(){try{var saved=localStorage.getItem('mmMealItems');if(saved)mealItems=JSON.parse(saved);var g=localStorage.getItem('mmCalorieGoal');if(g)dailyGoal=parseInt(g,10)||2000;}catch(e){}}
function saveState(){try{localStorage.setItem('mmMealItems',JSON.stringify(mealItems));localStorage.setItem('mmCalorieGoal',dailyGoal.toString());}catch(e){}}
function initTheme(){var saved=localStorage.getItem('mmDarkMode');var prefers=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches;if(saved==='true'||(saved===null&&prefers)){document.body.classList.add('nc-dark');if(els.themeBtn)els.themeBtn.innerHTML='<i class="fas fa-sun"></i>';}}
function toggleTheme(){document.body.classList.toggle('nc-dark');var isDark=document.body.classList.contains('nc-dark');localStorage.setItem('mmDarkMode',isDark.toString());if(els.themeBtn)els.themeBtn.innerHTML=isDark?'<i class="fas fa-sun"></i>':'<i class="fas fa-moon"></i>';}
function bindEvents(){if(els.themeBtn)els.themeBtn.onclick=toggleTheme;if(els.searchBtn)els.searchBtn.onclick=function(){doSearch();};if(els.searchInput)els.searchInput.onkeydown=function(e){if(e.key==='Enter'){e.preventDefault();doSearch();}};if(els.addBtn)els.addBtn.onclick=addFood;if(els.clearBtn)els.clearBtn.onclick=function(){if(confirm('Clear all meal items?')){mealItems=[];updateUI();}};if(els.goalSetBtn)els.goalSetBtn.onclick=setGoal;}
function doSearch(){var q=(els.searchInput.value||'').trim();if(!q)return;showEl(els.loader);hideEl(els.error);hideEl(els.resultsBox);hideEl(els.servingArea);hideEl(els.detailPanel);if(els.sourceInfo)els.sourceInfo.textContent='Searching multiple databases...';var sources={usda:0,calorieninjas:0,openfoodfacts:0,fatsecret:0};var allResults=[];var completed=0;var totalAPIs=4;function checkDone(){completed++;if(completed>=totalAPIs){hideEl(els.loader);var seen={};var unique=[];allResults.forEach(function(r){var key=r.name.toLowerCase().replace(/[^a-z0-9]/g,'').substring(0,30);if(!seen[key]){seen[key]=true;unique.push(r);}});searchResults=unique;if(unique.length>0){renderResults(unique);var parts=[];if(sources.usda)parts.push(sources.usda+' USDA');if(sources.calorieninjas)parts.push(sources.calorieninjas+' general');if(sources.fatsecret)parts.push(sources.fatsecret+' branded');if(sources.openfoodfacts)parts.push(sources.openfoodfacts+' packaged');if(els.sourceInfo)els.sourceInfo.textContent='Found '+unique.length+' foods: '+parts.join(' + ');}else{showError('No foods found. Try "chicken breast", "banana", or "rice".');}}}
searchUSDA(q,function(results){sources.usda=results.length;allResults=allResults.concat(results);checkDone();});searchCalorieNinjas(q,function(results){sources.calorieninjas=results.length;allResults=allResults.concat(results);checkDone();});searchOpenFoodFacts(q,function(results){sources.openfoodfacts=results.length;allResults=allResults.concat(results);checkDone();});searchFatSecret(q,function(results){sources.fatsecret=results.length;allResults=allResults.concat(results);checkDone();});}
function searchUSDA(query,callback){fetch(USDA_URL+'/foods/search?api_key='+USDA_KEY+'&query='+encodeURIComponent(query)+'&pageSize=8&dataType=Foundation,SR%20Legacy,Branded').then(function(r){return r.json();}).then(function(data){var results=[];if(data.foods){data.foods.forEach(function(f){var nuts={};(f.foodNutrients||[]).forEach(function(n){if(n.nutrientId===1008||n.nutrientNumber==='208')nuts.cal=n.value;if(n.nutrientId===1003||n.nutrientNumber==='203')nuts.pro=n.value;if(n.nutrientId===1005||n.nutrientNumber==='205')nuts.carb=n.value;if(n.nutrientId===1004||n.nutrientNumber==='204')nuts.fat=n.value;if(n.nutrientId===1079||n.nutrientId===1291||n.nutrientNumber==='291')nuts.fiber=n.value;if(n.nutrientId===2000||n.nutrientNumber==='269')nuts.sugar=n.value;if(n.nutrientId===1093||n.nutrientNumber==='307')nuts.sodium=n.value;if(n.nutrientId===1258||n.nutrientNumber==='606')nuts.satfat=n.value;if(n.nutrientId===1253||n.nutrientNumber==='601')nuts.chol=n.value;if(n.nutrientId===1092||n.nutrientNumber==='306')nuts.potassium=n.value;});results.push({source:'usda',name:f.description||'Unknown',brand:f.brandOwner||f.brandName||'',fdcId:f.fdcId,serving:'100g',serving_g:100,calories:r2(nuts.cal),protein:r2(nuts.pro),carbs:r2(nuts.carb),fat:r2(nuts.fat),fiber:r2(nuts.fiber),sugar:r2(nuts.sugar),sodium:r2(nuts.sodium),saturated_fat:r2(nuts.satfat),cholesterol:r2(nuts.chol),potassium:r2(nuts.potassium),});});}
callback(results);}).catch(function(){callback([]);});}
function getUSDADetail(fdcId,callback){fetch(USDA_URL+'/food/'+fdcId+'?api_key='+USDA_KEY).then(function(r){return r.json();}).then(function(data){var servings=[{desc:'100g (Standard)',size:100}];if(data.foodPortions){data.foodPortions.forEach(function(p){if(p.gramWeight){var label=(p.amount||'')+' '+(p.modifier||p.measureUnit&&p.measureUnit.name||'serving');servings.push({desc:label.trim()+' ('+p.gramWeight.toFixed(0)+'g)',size:p.gramWeight});}});}
var nuts={};(data.foodNutrients||[]).forEach(function(n){var id=n.nutrient?n.nutrient.id:n.nutrientId;var val=n.amount||n.value||0;if(id===1008)nuts.cal=val;if(id===1003)nuts.pro=val;if(id===1005)nuts.carb=val;if(id===1004)nuts.fat=val;if(id===1079||id===1291)nuts.fiber=val;if(id===2000)nuts.sugar=val;if(id===1093)nuts.sodium=val;if(id===1258)nuts.satfat=val;if(id===1253)nuts.chol=val;if(id===1092)nuts.potassium=val;});callback({servings:servings,nutrients:nuts,name:data.description});}).catch(function(){callback(null);});}
function searchCalorieNinjas(query,callback){fetch(PROXY+'?action=search_cn&q='+encodeURIComponent(query)).then(function(r){return r.json();}).then(function(data){callback(data.results||[]);}).catch(function(){callback([]);});}
function searchOpenFoodFacts(query,callback){var url='https://world.openfoodfacts.org/cgi/search.pl?search_terms='+
encodeURIComponent(query)+
'&search_simple=1&action=process&json=1&page_size=8'+
'&fields=product_name,brands,nutriments,serving_size,image_front_small_url';fetch(url,{headers:{'User-Agent':'MacroAndMeals/1.0'}}).then(function(r){var ct=r.headers.get('content-type')||'';if(ct.indexOf('json')===-1)throw new Error('Not JSON');return r.json();}).then(function(data){var results=[];if(data&&data.products){data.products.forEach(function(p){var n=p.nutriments||{};var name=p.product_name||'';if(!name)return;var brand=p.brands||'';if(brand)name+=' ('+brand+')';results.push({source:'openfoodfacts',name:name,serving:p.serving_size||'100g',serving_g:100,calories:r2(n['energy-kcal_100g']||n['energy-kcal']),protein:r2(n['proteins_100g']||n['proteins']),carbs:r2(n['carbohydrates_100g']||n['carbohydrates']),fat:r2(n['fat_100g']||n['fat']),fiber:r2(n['fiber_100g']||n['fiber']),sugar:r2(n['sugars_100g']||n['sugars']),sodium:r2((n['sodium_100g']||n['sodium']||0)*1000),saturated_fat:r2(n['saturated-fat_100g']||n['saturated-fat']),cholesterol:r2((n['cholesterol_100g']||0)*1000),potassium:r2((n['potassium_100g']||0)*1000),image:p.image_front_small_url||'',});});}
callback(results);}).catch(function(){callback([]);});}
function searchFatSecret(query,callback){fetch(PROXY+'?action=search_fs&q='+encodeURIComponent(query)).then(function(r){return r.json();}).then(function(data){callback(data.results||[]);}).catch(function(){callback([]);});}
function renderResults(foods){els.resultsBox.innerHTML='';foods.forEach(function(f){var div=document.createElement('div');div.className='nc-result';var srcMap={usda:['USDA','src-usda'],calorieninjas:['General','src-cn'],fatsecret:['Branded','src-fs'],openfoodfacts:['Packaged','src-off']};var src=srcMap[f.source]||['Other','src-cn'];div.innerHTML='<div class="nc-result-top">'+
'<span class="nc-result-name">'+escHtml(f.name)+'</span>'+
'<span class="nc-result-badge '+src[1]+'">'+src[0]+'</span>'+
'</div>'+
'<div class="nc-result-macros">'+
'<span class="nc-pill cal">'+(f.calories||0)+' cal</span>'+
'<span class="nc-pill pro">'+(f.protein||0)+'g P</span>'+
'<span class="nc-pill carb">'+(f.carbs||0)+'g C</span>'+
'<span class="nc-pill fat">'+(f.fat||0)+'g F</span>'+
'</div>';div.onclick=function(){selectFood(f,div);};els.resultsBox.appendChild(div);});showEl(els.resultsBox);}
function selectFood(f,el){var all=els.resultsBox.querySelectorAll('.nc-result');for(var i=0;i<all.length;i++)all[i].classList.remove('selected');el.classList.add('selected');selectedFood={name:f.name,cal:f.calories||0,pro:f.protein||0,carb:f.carbs||0,fat:f.fat||0,fiber:f.fiber||0,sugar:f.sugar||0,sodium:f.sodium||0,potassium:f.potassium||0,cholesterol:f.cholesterol||0,saturatedFat:f.saturated_fat||0,servingG:f.serving_g||100,servingDesc:f.serving||'100g',source:f.source,fdcId:f.fdcId||null,servings:[{desc:'100g (Standard)',size:100}],};if(f.source==='usda'&&f.fdcId){els.addBtn.disabled=true;if(els.selectedName)els.selectedName.textContent='Loading serving sizes...';showEl(els.servingArea);getUSDADetail(f.fdcId,function(detail){if(detail&&detail.servings){selectedFood.servings=detail.servings;if(detail.nutrients){selectedFood.cal=detail.nutrients.cal||selectedFood.cal;selectedFood.pro=detail.nutrients.pro||selectedFood.pro;selectedFood.carb=detail.nutrients.carb||selectedFood.carb;selectedFood.fat=detail.nutrients.fat||selectedFood.fat;selectedFood.fiber=detail.nutrients.fiber||selectedFood.fiber;selectedFood.sugar=detail.nutrients.sugar||selectedFood.sugar;selectedFood.sodium=detail.nutrients.sodium||selectedFood.sodium;selectedFood.saturatedFat=detail.nutrients.satfat||selectedFood.saturatedFat;selectedFood.cholesterol=detail.nutrients.chol||selectedFood.cholesterol;selectedFood.potassium=detail.nutrients.potassium||selectedFood.potassium;}}
populateServingUI();});}else{if(f.serving_g&&f.serving_g!==100){selectedFood.servings.push({desc:escHtml(f.serving||'Serving')+' ('+f.serving_g+'g)',size:f.serving_g});}
populateServingUI();}}
function populateServingUI(){els.servingSelect.innerHTML=selectedFood.servings.map(function(s,i){return'<option value="'+i+'">'+s.desc+'</option>';}).join('');if(els.selectedName)els.selectedName.textContent=selectedFood.name;if(els.selectedInfo){els.selectedInfo.innerHTML='<span class="nc-pill cal">'+r2(selectedFood.cal)+' cal</span> '+
'<span class="nc-pill pro">'+r2(selectedFood.pro)+'g protein</span> '+
'<span class="nc-pill carb">'+r2(selectedFood.carb)+'g carbs</span> '+
'<span class="nc-pill fat">'+r2(selectedFood.fat)+'g fat</span>';}
showDetailPanel();els.qtyInput.value='1';els.addBtn.disabled=false;showEl(els.servingArea);els.servingArea.scrollIntoView({behavior:'smooth',block:'nearest'});}
function showDetailPanel(){if(!els.detailPanel)return;var f=selectedFood;els.detailPanel.innerHTML='<div class="nc-detail-title">'+escHtml(f.name)+'</div>'+
'<div class="nc-detail-grid">'+
detailRow('Calories',r2(f.cal),'kcal')+
detailRow('Protein',r2(f.pro),'g')+
detailRow('Carbohydrates',r2(f.carb),'g')+
detailRow('Total Fat',r2(f.fat),'g')+
detailRow('Saturated Fat',r2(f.saturatedFat),'g')+
detailRow('Fiber',r2(f.fiber),'g')+
detailRow('Sugar',r2(f.sugar),'g')+
detailRow('Sodium',r2(f.sodium),'mg')+
detailRow('Cholesterol',r2(f.cholesterol),'mg')+
detailRow('Potassium',r2(f.potassium),'mg')+
'</div>'+
'<div class="nc-detail-note">Per 100g serving | Source: '+(f.source==='usda'?'USDA':f.source==='calorieninjas'?'General Database':f.source==='fatsecret'?'Branded Foods':'Packaged Products')+'</div>';showEl(els.detailPanel);}
function detailRow(label,value,unit){return'<div class="nc-detail-row"><span class="nc-detail-lbl">'+label+'</span><span class="nc-detail-val">'+value+' '+unit+'</span></div>';}
function addFood(){if(!selectedFood)return;var qty=parseFloat(els.qtyInput.value)||1;var srvIdx=parseInt(els.servingSelect.value,10)||0;var srv=selectedFood.servings[srvIdx]||{size:100};var factor=(qty*srv.size)/100;mealItems.push({id:Date.now(),name:selectedFood.name,cal:selectedFood.cal*factor,pro:selectedFood.pro*factor,carb:selectedFood.carb*factor,fat:selectedFood.fat*factor,fiber:selectedFood.fiber*factor,sugar:selectedFood.sugar*factor,sodium:selectedFood.sodium*factor,satfat:selectedFood.saturatedFat*factor,chol:selectedFood.cholesterol*factor,potassium:selectedFood.potassium*factor,qty:qty,serving:els.servingSelect.options[els.servingSelect.selectedIndex].text,});updateUI();showToast('Added to meal!');hideEl(els.servingArea);hideEl(els.resultsBox);hideEl(els.detailPanel);els.searchInput.value='';selectedFood=null;}
function setGoal(){var v=parseInt(els.goalInput.value,10);if(v>=500){dailyGoal=v;saveState();updateUI();showToast('Goal updated to '+v+' kcal');}}
function updateUI(){saveState();els.tableBody.innerHTML='';mealItems.forEach(function(item){var tr=document.createElement('tr');tr.innerHTML='<td><strong>'+escHtml(item.name)+'</strong><br><small class="nc-serving-label">'+escHtml(item.serving)+' x'+item.qty+'</small></td>'+
'<td class="nc-tc"><strong>'+item.cal.toFixed(0)+'</strong></td>'+
'<td class="nc-tc">'+item.pro.toFixed(1)+'g</td>'+
'<td class="nc-tc">'+item.carb.toFixed(1)+'g</td>'+
'<td class="nc-tc">'+item.fat.toFixed(1)+'g</td>'+
'<td class="nc-tc"><button class="nc-remove-btn" data-id="'+item.id+'"><i class="fas fa-times"></i></button></td>';els.tableBody.appendChild(tr);});var btns=els.tableBody.querySelectorAll('.nc-remove-btn');for(var i=0;i<btns.length;i++){btns[i].onclick=function(){var id=parseInt(this.getAttribute('data-id'),10);mealItems=mealItems.filter(function(m){return m.id!==id;});updateUI();};}
var has=mealItems.length>0;if(els.emptyState)els.emptyState.style.display=has?'none':'';if(els.tableWrap)els.tableWrap.style.display=has?'':'none';if(els.clearBtn)els.clearBtn.style.display=has?'':'none';if(els.itemCount)els.itemCount.textContent=mealItems.length;var t={cal:0,pro:0,carb:0,fat:0,fiber:0,sugar:0,sodium:0,satfat:0,chol:0,potassium:0};mealItems.forEach(function(m){t.cal+=m.cal;t.pro+=m.pro;t.carb+=m.carb;t.fat+=m.fat;t.fiber+=m.fiber;t.sugar+=m.sugar;t.sodium+=m.sodium;t.satfat+=(m.satfat||0);t.chol+=(m.chol||0);t.potassium+=(m.potassium||0);});setText(els.totalCal,t.cal.toFixed(0)+' kcal');setText(els.totalPro,t.pro.toFixed(1));setText(els.totalCarb,t.carb.toFixed(1));setText(els.totalFat,t.fat.toFixed(1));setText(els.totalFiber,t.fiber.toFixed(1));setText(els.totalSugar,t.sugar.toFixed(1));setText(els.totalSodium,t.sodium.toFixed(0));setText(els.totalSatFat,t.satfat.toFixed(1));setText(els.totalCholesterol,t.chol.toFixed(0));setText(els.totalPotassium,t.potassium.toFixed(0));var total=t.pro+t.carb+t.fat;var pp=total?(t.pro/total)*100:33.3;var cp=total?(t.carb/total)*100:33.3;var fp=total?(t.fat/total)*100:33.3;if(els.proSeg){els.proSeg.style.width=pp+'%';els.proSeg.textContent=pp>8?pp.toFixed(0)+'%':'';}
if(els.carbSeg){els.carbSeg.style.width=cp+'%';els.carbSeg.textContent=cp>8?cp.toFixed(0)+'%':'';}
if(els.fatSeg){els.fatSeg.style.width=fp+'%';els.fatSeg.textContent=fp>8?fp.toFixed(0)+'%':'';}
setText(els.proPct,pp.toFixed(0)+'%');setText(els.carbPct,cp.toFixed(0)+'%');setText(els.fatPct,fp.toFixed(0)+'%');var gp=dailyGoal>0?(t.cal/dailyGoal)*100:0;if(els.goalBar){els.goalBar.style.width=Math.min(gp,100)+'%';els.goalBar.style.background=gp>100?'#ef4444':'';}
setText(els.goalPct,gp.toFixed(0)+'%');setText(els.goalDisplay,'Goal: '+dailyGoal+' kcal');}
function showEl(el){if(el)el.classList.remove('nc-hidden');}
function hideEl(el){if(el)el.classList.add('nc-hidden');}
function setText(el,t){if(el)el.textContent=t;}
function r2(v){return Math.round((v||0)*10)/10;}
function showError(msg){if(els.error){els.error.textContent=msg;showEl(els.error);}}
function escHtml(s){var d=document.createElement('div');d.appendChild(document.createTextNode(s||''));return d.innerHTML;}
function showToast(msg){var t=document.createElement('div');t.className='nc-toast';t.textContent=msg;document.body.appendChild(t);setTimeout(function(){t.classList.add('show');},10);setTimeout(function(){t.classList.remove('show');setTimeout(function(){t.remove();},300);},2500);}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}})();