(function(){'use strict';var P='nc-';var PROXY='/api/nutrition-proxy.php';var $=function(id){return document.getElementById(P+id);};var els={themeBtn:$('theme-toggle'),searchInput:$('search-input'),searchBtn:$('search-btn'),loader:$('loader'),error:$('error'),resultsBox:$('results'),servingArea:$('serving-area'),qtyInput:$('qty'),servingSelect:$('serving-sel'),addBtn:$('add-btn'),totalCal:$('total-cal'),totalPro:$('total-pro'),totalCarb:$('total-carb'),totalFat:$('total-fat'),totalFiber:$('total-fiber'),totalSugar:$('total-sugar'),totalSodium:$('total-sodium'),proPct:$('pro-pct'),carbPct:$('carb-pct'),fatPct:$('fat-pct'),proSeg:$('pro-seg'),carbSeg:$('carb-seg'),fatSeg:$('fat-seg'),goalBar:$('goal-bar'),goalPct:$('goal-pct'),goalDisplay:$('goal-display'),goalInput:$('goal-input'),goalSetBtn:$('goal-set'),tableBody:$('table-body'),tableWrap:$('table-wrap'),emptyState:$('empty'),clearBtn:$('clear-btn'),sourceInfo:$('source-info'),selectedName:$('selected-name'),selectedInfo:$('selected-info'),};var mealItems=[];var selectedFood=null;var dailyGoal=2000;function init(){loadState();initTheme();bindEvents();updateUI();}
function loadState(){try{var saved=localStorage.getItem('mmMealItems');if(saved)mealItems=JSON.parse(saved);var g=localStorage.getItem('mmCalorieGoal');if(g)dailyGoal=parseInt(g,10)||2000;}catch(e){}}
function saveState(){try{localStorage.setItem('mmMealItems',JSON.stringify(mealItems));localStorage.setItem('mmCalorieGoal',dailyGoal.toString());}catch(e){}}
function initTheme(){var saved=localStorage.getItem('mmDarkMode');var prefers=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches;if(saved==='true'||(saved===null&&prefers)){document.body.classList.add('nc-dark');if(els.themeBtn)els.themeBtn.innerHTML='<i class="fas fa-sun"></i>';}}
function toggleTheme(){document.body.classList.toggle('nc-dark');var isDark=document.body.classList.contains('nc-dark');localStorage.setItem('mmDarkMode',isDark.toString());if(els.themeBtn)els.themeBtn.innerHTML=isDark?'<i class="fas fa-sun"></i>':'<i class="fas fa-moon"></i>';}
function bindEvents(){if(els.themeBtn)els.themeBtn.onclick=toggleTheme;if(els.searchBtn)els.searchBtn.onclick=function(){doSearch();};if(els.searchInput)els.searchInput.onkeydown=function(e){if(e.key==='Enter'){e.preventDefault();doSearch();}};if(els.addBtn)els.addBtn.onclick=addFood;if(els.clearBtn)els.clearBtn.onclick=function(){if(confirm('Clear all meal items?')){mealItems=[];updateUI();}};if(els.goalSetBtn)els.goalSetBtn.onclick=setGoal;}
function doSearch(){var q=(els.searchInput.value||'').trim();if(!q)return;showEl(els.loader);hideEl(els.error);hideEl(els.resultsBox);hideEl(els.servingArea);if(els.sourceInfo)els.sourceInfo.textContent='';fetch(PROXY+'?action=search&q='+encodeURIComponent(q)).then(function(r){return r.json();}).then(function(data){hideEl(els.loader);if(data.results&&data.results.length>0){renderResults(data.results);if(els.sourceInfo&&data.sources){var parts=[];if(data.sources.calorieninjas)parts.push(data.sources.calorieninjas+' general');if(data.sources.fatsecret)parts.push(data.sources.fatsecret+' branded');if(data.sources.openfoodfacts)parts.push(data.sources.openfoodfacts+' packaged');els.sourceInfo.textContent='Found: '+parts.join(' + ')+' items';}}else{showError('No foods found. Try a different search term.');}}).catch(function(){hideEl(els.loader);showError('Search failed. Please check your connection and try again.');});}
function renderResults(foods){els.resultsBox.innerHTML='';foods.forEach(function(f,i){var div=document.createElement('div');div.className='nc-result';var sourceLabel=f.source==='calorieninjas'?'General':f.source==='fatsecret'?'Branded':'Packaged';var sourceCls=f.source==='calorieninjas'?'src-cn':f.source==='fatsecret'?'src-fs':'src-off';div.innerHTML='<div class="nc-result-top">'+
'<span class="nc-result-name">'+escHtml(f.name)+'</span>'+
'<span class="nc-result-badge '+sourceCls+'">'+sourceLabel+'</span>'+
'</div>'+
'<div class="nc-result-macros">'+
'<span class="nc-pill cal">'+f.calories+' cal</span>'+
'<span class="nc-pill pro">'+f.protein+'g P</span>'+
'<span class="nc-pill carb">'+f.carbs+'g C</span>'+
'<span class="nc-pill fat">'+f.fat+'g F</span>'+
'</div>';div.onclick=function(){selectFood(f,div);};els.resultsBox.appendChild(div);});showEl(els.resultsBox);}
function selectFood(f,el){var all=els.resultsBox.querySelectorAll('.nc-result');for(var i=0;i<all.length;i++)all[i].classList.remove('selected');el.classList.add('selected');selectedFood={name:f.name,cal:f.calories,pro:f.protein,carb:f.carbs,fat:f.fat,fiber:f.fiber||0,sugar:f.sugar||0,sodium:f.sodium||0,potassium:f.potassium||0,cholesterol:f.cholesterol||0,saturatedFat:f.saturated_fat||0,servingG:f.serving_g||100,servingDesc:f.serving||'100g',source:f.source,};els.servingSelect.innerHTML='<option value="100">100g (Standard)</option>'+
'<option value="'+selectedFood.servingG+'">'+escHtml(selectedFood.servingDesc)+' ('+selectedFood.servingG+'g)</option>';if(els.selectedName)els.selectedName.textContent=selectedFood.name;if(els.selectedInfo){els.selectedInfo.innerHTML='<span class="nc-pill cal">'+selectedFood.cal+' cal</span> '+
'<span class="nc-pill pro">'+selectedFood.pro+'g protein</span> '+
'<span class="nc-pill carb">'+selectedFood.carb+'g carbs</span> '+
'<span class="nc-pill fat">'+selectedFood.fat+'g fat</span>';}
els.qtyInput.value='1';els.addBtn.disabled=false;showEl(els.servingArea);els.servingArea.scrollIntoView({behavior:'smooth',block:'nearest'});}
function addFood(){if(!selectedFood)return;var qty=parseFloat(els.qtyInput.value)||1;var srvG=parseFloat(els.servingSelect.value)||100;var factor=(qty*srvG)/100;mealItems.push({id:Date.now(),name:selectedFood.name,cal:selectedFood.cal*factor,pro:selectedFood.pro*factor,carb:selectedFood.carb*factor,fat:selectedFood.fat*factor,fiber:selectedFood.fiber*factor,sugar:selectedFood.sugar*factor,sodium:selectedFood.sodium*factor,qty:qty,serving:els.servingSelect.options[els.servingSelect.selectedIndex].text,});updateUI();showToast('Added to meal!');hideEl(els.servingArea);hideEl(els.resultsBox);els.searchInput.value='';selectedFood=null;}
function setGoal(){var v=parseInt(els.goalInput.value,10);if(v>=500){dailyGoal=v;saveState();updateUI();showToast('Goal updated to '+v+' kcal');}}
function updateUI(){saveState();els.tableBody.innerHTML='';mealItems.forEach(function(item){var tr=document.createElement('tr');tr.innerHTML='<td><strong>'+escHtml(item.name)+'</strong><br><small>'+escHtml(item.serving)+'</small></td>'+
'<td class="nc-tc">'+item.cal.toFixed(0)+'</td>'+
'<td class="nc-tc">'+item.pro.toFixed(1)+'g</td>'+
'<td class="nc-tc">'+item.carb.toFixed(1)+'g</td>'+
'<td class="nc-tc">'+item.fat.toFixed(1)+'g</td>'+
'<td class="nc-tc"><button class="nc-remove-btn" data-id="'+item.id+'"><i class="fas fa-times"></i></button></td>';els.tableBody.appendChild(tr);});var btns=els.tableBody.querySelectorAll('.nc-remove-btn');for(var i=0;i<btns.length;i++){btns[i].onclick=function(){var id=parseInt(this.getAttribute('data-id'),10);mealItems=mealItems.filter(function(m){return m.id!==id;});updateUI();};}
var has=mealItems.length>0;if(els.emptyState){els.emptyState.style.display=has?'none':'';}
if(els.tableWrap){els.tableWrap.style.display=has?'':'none';}
if(els.clearBtn){els.clearBtn.style.display=has?'':'none';}
var t={cal:0,pro:0,carb:0,fat:0,fiber:0,sugar:0,sodium:0};mealItems.forEach(function(m){t.cal+=m.cal;t.pro+=m.pro;t.carb+=m.carb;t.fat+=m.fat;t.fiber+=m.fiber;t.sugar+=m.sugar;t.sodium+=m.sodium;});setText(els.totalCal,t.cal.toFixed(0)+' kcal');setText(els.totalPro,t.pro.toFixed(1));setText(els.totalCarb,t.carb.toFixed(1));setText(els.totalFat,t.fat.toFixed(1));setText(els.totalFiber,t.fiber.toFixed(1));setText(els.totalSugar,t.sugar.toFixed(1));setText(els.totalSodium,t.sodium.toFixed(0));var total=t.pro+t.carb+t.fat;var pp=total?(t.pro/total)*100:33.3;var cp=total?(t.carb/total)*100:33.3;var fp=total?(t.fat/total)*100:33.3;if(els.proSeg){els.proSeg.style.width=pp+'%';els.proSeg.textContent=pp>8?pp.toFixed(0)+'%':'';}
if(els.carbSeg){els.carbSeg.style.width=cp+'%';els.carbSeg.textContent=cp>8?cp.toFixed(0)+'%':'';}
if(els.fatSeg){els.fatSeg.style.width=fp+'%';els.fatSeg.textContent=fp>8?fp.toFixed(0)+'%':'';}
setText(els.proPct,pp.toFixed(0)+'%');setText(els.carbPct,cp.toFixed(0)+'%');setText(els.fatPct,fp.toFixed(0)+'%');var gp=(t.cal/dailyGoal)*100;if(els.goalBar){els.goalBar.style.width=Math.min(gp,100)+'%';els.goalBar.style.background=gp>100?'#ef4444':'';}
setText(els.goalPct,gp.toFixed(0)+'%');setText(els.goalDisplay,'Goal: '+dailyGoal+' kcal');}
function showEl(el){if(el)el.classList.remove('nc-hidden');}
function hideEl(el){if(el)el.classList.add('nc-hidden');}
function setText(el,t){if(el)el.textContent=t;}
function showError(msg){if(els.error){els.error.textContent=msg;showEl(els.error);}}
function escHtml(s){var d=document.createElement('div');d.appendChild(document.createTextNode(s||''));return d.innerHTML;}
function showToast(msg){var t=document.createElement('div');t.className='nc-toast';t.textContent=msg;document.body.appendChild(t);setTimeout(function(){t.classList.add('show');},10);setTimeout(function(){t.classList.remove('show');setTimeout(function(){t.remove();},300);},2500);}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}})();