function initRestaurant(data){'use strict';if(!data){var appEl=document.getElementById('rest-app');var slug=appEl?appEl.getAttribute('data-restaurant'):null;if(!slug){var path=window.location.pathname.replace(/^\/|\/$/g,'');if(path)slug=path;}
if(slug){fetch('/data/restaurants/'+slug+'.json').then(function(r){return r.json();}).then(function(json){renderRestaurant(json);}).catch(function(err){console.warn('Restaurant JSON not found, trying inline HTML mode');initFromHTML();});return;}
initFromHTML();return;}
renderRestaurant(data);}
function renderRestaurant(data){var grid=document.getElementById('rest-grid');var tabs=document.getElementById('rest-tabs');var summary=document.getElementById('rest-summary');var wrapper=document.getElementById('rest-layout-wrapper');if(!wrapper){var section=document.querySelector('.section .container')||document.querySelector('.section');if(!section)return;wrapper=document.createElement('div');wrapper.id='rest-layout-wrapper';section.appendChild(wrapper);}
if(!grid||!tabs){wrapper.innerHTML=buildRestaurantHTML(data);grid=document.getElementById('rest-grid');tabs=document.getElementById('rest-tabs');summary=document.getElementById('rest-summary');}else{rebuildGrid(grid,tabs,data);}
initInteractions(grid,tabs,summary);}
function buildRestaurantHTML(data){var cats=data.categories||[];var tabsHTML='<div class="rest-left-col"><div class="calc-card">';tabsHTML+='<div id="rest-tabs" class="cat-tabs"><div class="cat-tabs-scroll">';cats.forEach(function(cat,i){tabsHTML+='<button class="cat-tab'+(i===0?' active':'')+'" data-cat="'+escHTML(cat.name)+'">';tabsHTML+=escHTML(cat.name)+' <span class="cat-count">'+cat.items.length+'</span></button>';});tabsHTML+='</div><div class="rest-search"><input type="text" id="rest-search-input" class="rest-search-input" placeholder="Search items..."></div></div>';tabsHTML+='<div id="rest-grid" class="menu-grid">';cats.forEach(function(cat,i){tabsHTML+='<div class="rest-cat-group" data-category="'+escHTML(cat.name)+'"'+(i>0?' style="display:none"':'')+'>';cat.items.forEach(function(item){tabsHTML+=buildItemHTML(item);});tabsHTML+='</div>';});tabsHTML+='</div>';tabsHTML+='<div class="rest-actions"><button class="btn btn-primary" id="add-to-meal">Add Selected to My Meal</button></div>';tabsHTML+='</div></div>';tabsHTML+='<div class="rest-right-col">';tabsHTML+='<div id="rest-summary"><div class="meal-summary">';tabsHTML+='<h3>My Meal <span class="meal-count">(0 items)</span> <button class="reset-btn" id="reset-meal">Reset</button></h3>';tabsHTML+='<div class="meal-progress"><div class="meal-progress-bar" style="width:0%"></div></div>';tabsHTML+='<div class="meal-progress-text">0 / 2,000 cal (0%)</div>';tabsHTML+='<div class="meal-totals">';tabsHTML+='<div class="meal-total pill-cal"><div class="num">0</div><div class="lbl">Calories</div></div>';tabsHTML+='<div class="meal-total pill-pro"><div class="num">0g</div><div class="lbl">Protein</div></div>';tabsHTML+='<div class="meal-total pill-carb"><div class="num">0g</div><div class="lbl">Carbs</div></div>';tabsHTML+='<div class="meal-total pill-fat"><div class="num">0g</div><div class="lbl">Fat</div></div>';tabsHTML+='</div>';tabsHTML+='<div class="meal-items"><div class="empty-msg">No items added yet. Click items above and press "Add to My Meal".</div></div>';tabsHTML+='</div></div></div>';return tabsHTML;}
function buildItemHTML(item){var attrs=' data-name="'+escHTML(item.name)+'"';attrs+=' data-calories="'+(item.calories||0)+'"';attrs+=' data-protein="'+(item.protein||0)+'"';attrs+=' data-carbs="'+(item.carbs||0)+'"';attrs+=' data-fat="'+(item.fat||0)+'"';attrs+=' data-fiber="'+(item.fiber||0)+'"';attrs+=' data-sodium="'+(item.sodium||0)+'"';if(item.cholesterol)attrs+=' data-cholesterol="'+item.cholesterol+'"';if(item.saturated_fat)attrs+=' data-saturated-fat="'+item.saturated_fat+'"';if(item.sugars)attrs+=' data-sugars="'+item.sugars+'"';if(item.trans_fat)attrs+=' data-trans-fat="'+item.trans_fat+'"';var html='<div class="menu-item"'+attrs+'>';html+='<div class="menu-item-header"><h4>'+escHTML(item.name)+'</h4></div>';html+='<div class="menu-item-cal">'+Math.round(item.calories||0)+' cal</div>';html+='<div class="macros">';html+='<span class="macro-pro">P: '+Math.round(item.protein||0)+'g</span> ';html+='<span class="macro-carb">C: '+Math.round(item.carbs||0)+'g</span> ';html+='<span class="macro-fat">F: '+Math.round(item.fat||0)+'g</span>';html+='</div></div>';return html;}
function rebuildGrid(grid,tabs,data){var cats=data.categories||[];var scrollDiv=tabs.querySelector('.cat-tabs-scroll');if(scrollDiv){scrollDiv.innerHTML='';cats.forEach(function(cat,i){var btn=document.createElement('button');btn.className='cat-tab'+(i===0?' active':'');btn.setAttribute('data-cat',cat.name);btn.innerHTML=escHTML(cat.name)+' <span class="cat-count">'+cat.items.length+'</span>';scrollDiv.appendChild(btn);});}
grid.innerHTML='';cats.forEach(function(cat,i){var groupDiv=document.createElement('div');groupDiv.className='rest-cat-group';groupDiv.setAttribute('data-category',cat.name);if(i>0)groupDiv.style.display='none';cat.items.forEach(function(item){groupDiv.innerHTML+=buildItemHTML(item);});grid.appendChild(groupDiv);});}
function initFromHTML(){var grid=document.getElementById('rest-grid');var tabs=document.getElementById('rest-tabs');var summary=document.getElementById('rest-summary');if(!grid)return;initInteractions(grid,tabs,summary);}
function initInteractions(grid,tabs,summary){if(!grid)return;var meal=[];var dailyCal=2000;if(tabs){tabs.addEventListener('click',function(e){var tab=e.target.closest('.cat-tab');if(!tab)return;Array.from(tabs.querySelectorAll('.cat-tab')).forEach(function(t){t.classList.remove('active');});tab.classList.add('active');var cat=tab.getAttribute('data-cat');Array.from(grid.querySelectorAll('.rest-cat-group')).forEach(function(g){g.style.display=(cat==='all'||g.getAttribute('data-category')===cat)?'':'none';});});}
var searchInput=document.getElementById('rest-search-input');if(searchInput){searchInput.addEventListener('input',function(){var term=searchInput.value.toLowerCase().trim();if(term){Array.from(grid.querySelectorAll('.rest-cat-group')).forEach(function(g){g.style.display='';});if(tabs)Array.from(tabs.querySelectorAll('.cat-tab')).forEach(function(t){t.classList.remove('active');});}else{if(tabs){var firstTab=tabs.querySelector('.cat-tab');if(firstTab){firstTab.classList.add('active');var firstCat=firstTab.getAttribute('data-cat');Array.from(grid.querySelectorAll('.rest-cat-group')).forEach(function(g){g.style.display=g.getAttribute('data-category')===firstCat?'':'none';});}}}
Array.from(grid.querySelectorAll('.menu-item')).forEach(function(item){var name=(item.getAttribute('data-name')||'').toLowerCase();item.style.display=(!term||name.indexOf(term)!==-1)?'':'none';});});}
grid.addEventListener('click',function(e){var item=e.target.closest('.menu-item');if(!item)return;item.classList.toggle('selected');});var addBtn=document.getElementById('add-to-meal')||document.getElementById('add-meal-btn');if(addBtn){addBtn.addEventListener('click',function(){Array.from(grid.querySelectorAll('.menu-item.selected')).forEach(function(item){meal.push({name:item.getAttribute('data-name')||'Item',calories:parseFloat(item.getAttribute('data-calories'))||0,protein:parseFloat(item.getAttribute('data-protein'))||0,carbs:parseFloat(item.getAttribute('data-carbs'))||0,fat:parseFloat(item.getAttribute('data-fat'))||0,fiber:parseFloat(item.getAttribute('data-fiber'))||0,sodium:parseFloat(item.getAttribute('data-sodium'))||0});item.classList.remove('selected');});updateSummary();});}
var resetBtn=document.getElementById('reset-meal');if(resetBtn){resetBtn.addEventListener('click',function(){meal=[];updateSummary();});}
if(summary){summary.addEventListener('click',function(e){if(e.target.classList.contains('remove-item')){var idx=parseInt(e.target.getAttribute('data-idx'));if(!isNaN(idx)){meal.splice(idx,1);updateSummary();}}});}
function updateSummary(){if(!summary)return;var totals=meal.reduce(function(acc,m){acc.calories+=m.calories;acc.protein+=m.protein;acc.carbs+=m.carbs;acc.fat+=m.fat;acc.fiber+=m.fiber;acc.sodium+=m.sodium;return acc;},{calories:0,protein:0,carbs:0,fat:0,fiber:0,sodium:0});var pct=Math.min(Math.round(totals.calories/dailyCal*100),100);var el;el=summary.querySelector('.meal-count');if(el)el.textContent='('+meal.length+' item'+(meal.length!==1?'s':'')+')';el=summary.querySelector('.meal-progress-bar');if(el)el.style.width=pct+'%';el=summary.querySelector('.meal-progress-text');if(el)el.textContent=Math.round(totals.calories).toLocaleString()+' / '+dailyCal.toLocaleString()+' cal ('+pct+'%)';var nums=summary.querySelectorAll('.meal-total .num');if(nums.length>=4){nums[0].textContent=Math.round(totals.calories).toLocaleString();nums[1].textContent=Math.round(totals.protein)+'g';nums[2].textContent=Math.round(totals.carbs)+'g';nums[3].textContent=Math.round(totals.fat)+'g';}
var itemsDiv=summary.querySelector('.meal-items');if(itemsDiv){if(meal.length===0){itemsDiv.innerHTML='<div class="empty-msg">No items added yet. Click items above and press "Add to My Meal".</div>';}else{itemsDiv.innerHTML=meal.map(function(m,i){return'<div class="meal-item"><span>'+escHTML(m.name)+'</span><span class="meal-item-cal">'+Math.round(m.calories)+' cal</span><button class="remove-item" data-idx="'+i+'">&times;</button></div>';}).join('');}}}}
function escHTML(s){var div=document.createElement('div');div.appendChild(document.createTextNode(s));return div.innerHTML;}